version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
        
    steps:
      - checkout
      - run:
          command: ./gradlew ktlint
      - run:
          command: ./gradlew :data:testDebugUnitTest
      - run:
          command: ./gradlew :domain:testDebugUnitTest
